



Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]

  (1..1).each do |i|
  config.vm.define "Leon-test-02-webserver#{i}" do |web_config|
      web_config.vm.box = "ubuntu/xenial64"
      web_config.vm.hostname = "Leon-test-02-webserver#{i}"
      web_config.vm.network "private_network", ip: "192.168.7.1#{i}" 
      web_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      web_config.vm.provider "virtualbox" do |vb|
        vb.name = "Leon-test-02-webserver#{i}"
        vb.gui = false
        vb.memory = "512"   
      end
  end
end

end
