---
- hosts: web
  become: True
  tasks:
    - name: install apache2
      apt:
        name: apache2
        state: present
        update_cache: yes
    - name: install php
      apt:
        name: php libapache2-mod-php
        state: present
        update_cache: yes