---
- name: Ensure MySQL users are present.
  mysql_user:
    name: "Admin1"
    host: "192.168.102.5"
    password: "Pass1"
    priv: "{{ item.priv | default('*.*:USAGE') }}"
    state: "{{ item.state | default('present') }}"
    append_privs: "{{ item.append_privs | default('no') }}"
    encrypted: "{{ item.encrypted | default('no') }}"
  with_items: "{{ mysql_users }}"
  no_log: false
