- name: Delete default page
  file:
    path: /var/www/html/index.html
    state: absent
  
- name: Copy index.php
  copy:
    src: index.php.j2
    dest: /var/www/html/index.php
    mode: 0644
  notify: restart apache2



