---
- name: Install PHP
  apt:
    name: php
    state: present
    update_cache: yes

- name: Install libapache2
  apt:
    name: libapache2-mod-php
    state: present
    update_cache: yes

- name: Install php-mysql
  apt:
    name: php-mysql
    state: present
    update_cache: yes
