# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_rsa", "~/.vagrant.d/insecure_private_key"]


  config.vm.define "Klant2-lb" do |lb1_config|
      lb1_config.vm.box = "ubuntu/xenial64"
      lb1_config.vm.hostname = "Klant2-lb"
      lb1_config.vm.network "private_network", ip: "192.168.102.10" 
      lb1_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      lb1_config.vm.provider "virtualbox" do |vb|
        vb.name = "loadbalancer1"
        vb.gui = false
        vb.memory = "1024"   
      end
  end

  config.vm.define "Klant2-webserver1" do |web1_config|
      web1_config.vm.box = "ubuntu/xenial64"
      web1_config.vm.hostname = "Klant2-webserver1"
      web1_config.vm.network "private_network", ip: "192.168.102.5" 
      web1_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      web1_config.vm.provider "virtualbox" do |vb|
        vb.name = "webserver1"
        vb.gui = false
        vb.memory = "1024"   
      end
  end

  config.vm.define "Klant2-webserver2" do |web2_config|
      web2_config.vm.box = "ubuntu/xenial64"
      web2_config.vm.hostname = "Klant2-webserver2"
      web2_config.vm.network "private_network", ip: "192.168.102.6" 
      web2_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      web2_config.vm.provider "virtualbox" do |vb|
        vb.name = "webserver2"
        vb.gui = false
        vb.memory = "1024"   
      end
  end

  config.vm.define "Klant2-db" do |db_config|
      db_config.vm.box = "ubuntu/xenial64"
      db_config.vm.hostname = "Klant2-db"
      db_config.vm.network "private_network", ip: "192.168.102.20" 
      db_config.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "~/.ssh/authorized_keys"
      db_config.vm.provider "virtualbox" do |vb|
        vb.name = "database"
        vb.gui = false
        vb.memory = "1024"   
      end
  end
end
